# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install sqlalchemy

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    # - make models.html
    - ls -al
    - make IDB3.log
    - ls -al
    - make test
    - ls -al
    - make check
